services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seafi_backend_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - seafi_db:/src/data

volumes:
  seafi_db: